package com.sunway.vo;
// Generated 2017-4-13 10:45:02 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Pgt00401 generated by hbm2java
 */
public class Pgt00401 implements java.io.Serializable {
	private static final long serialVersionUID = 2645661738105773095L;
	
	private String id;
	private String szqy;
	private String zldz;
	private String jzjg;
	private String ghyt;
	private String lc;
	private String bdcdyh;
	private BigDecimal jzmj;
	private String qllx;
	private String qlxz;
	private String qlqtzk;
	private String syqx;
	private String jcnf;
	private BigDecimal htjg;
	private String zhxz;
	private BigDecimal pgjg;
	private String qlr;
	private String gyqk;
	private String bdczh;
	private String note;
	private String cd00002Czr;
	private Date updDate;
	private String cd00001Ssgx;
	private Date jysj;

	public Pgt00401() {
	}

	public Pgt00401(String id, BigDecimal jzmj, BigDecimal htjg, BigDecimal pgjg) {
		this.id = id;
		this.jzmj = jzmj;
		this.htjg = htjg;
		this.pgjg = pgjg;
	}

	public Pgt00401(String id, String szqy, String zldz, String jzjg, String ghyt, String lc, String bdcdyh,
			BigDecimal jzmj, String qllx, String qlxz, String qlqtzk, String syqx, String jcnf, BigDecimal htjg,
			String zhxz, BigDecimal pgjg, String qlr, String gyqk, String bdczh, String note, String cd00002Czr, 
			Date updDate, String cd00001Ssgx, Date jysj) {
		this.id = id;
		this.szqy = szqy;
		this.zldz = zldz;
		this.jzjg = jzjg;
		this.ghyt = ghyt;
		this.lc = lc;
		this.bdcdyh = bdcdyh;
		this.jzmj = jzmj;
		this.qllx = qllx;
		this.qlxz = qlxz;
		this.qlqtzk = qlqtzk;
		this.syqx = syqx;
		this.jcnf = jcnf;
		this.htjg = htjg;
		this.zhxz = zhxz;
		this.pgjg = pgjg;
		this.qlr = qlr;
		this.gyqk = gyqk;
		this.bdczh = bdczh;
		this.note = note;
		this.cd00002Czr = cd00002Czr;
		this.updDate = updDate;
		this.cd00001Ssgx = cd00001Ssgx;
		this.jysj = jysj;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getSzqy() {
		return this.szqy;
	}

	public void setSzqy(String szqy) {
		this.szqy = szqy;
	}

	public String getZldz() {
		return this.zldz;
	}

	public void setZldz(String zldz) {
		this.zldz = zldz;
	}

	public String getJzjg() {
		return this.jzjg;
	}

	public void setJzjg(String jzjg) {
		this.jzjg = jzjg;
	}

	public String getGhyt() {
		return this.ghyt;
	}

	public void setGhyt(String ghyt) {
		this.ghyt = ghyt;
	}

	public String getLc() {
		return this.lc;
	}

	public void setLc(String lc) {
		this.lc = lc;
	}

	public String getBdcdyh() {
		return this.bdcdyh;
	}

	public void setBdcdyh(String bdcdyh) {
		this.bdcdyh = bdcdyh;
	}

	public BigDecimal getJzmj() {
		return this.jzmj;
	}

	public void setJzmj(BigDecimal jzmj) {
		this.jzmj = jzmj;
	}

	public String getQllx() {
		return this.qllx;
	}

	public void setQllx(String qllx) {
		this.qllx = qllx;
	}

	public String getQlxz() {
		return this.qlxz;
	}

	public void setQlxz(String qlxz) {
		this.qlxz = qlxz;
	}

	public String getQlqtzk() {
		return this.qlqtzk;
	}

	public void setQlqtzk(String qlqtzk) {
		this.qlqtzk = qlqtzk;
	}

	public String getSyqx() {
		return this.syqx;
	}

	public void setSyqx(String syqx) {
		this.syqx = syqx;
	}

	public String getJcnf() {
		return this.jcnf;
	}

	public void setJcnf(String jcnf) {
		this.jcnf = jcnf;
	}

	public BigDecimal getHtjg() {
		return this.htjg;
	}

	public void setHtjg(BigDecimal htjg) {
		this.htjg = htjg;
	}

	public String getZhxz() {
		return this.zhxz;
	}

	public void setZhxz(String zhxz) {
		this.zhxz = zhxz;
	}

	public BigDecimal getPgjg() {
		return this.pgjg;
	}

	public void setPgjg(BigDecimal pgjg) {
		this.pgjg = pgjg;
	}

	public String getQlr() {
		return this.qlr;
	}

	public void setQlr(String qlr) {
		this.qlr = qlr;
	}

	public String getGyqk() {
		return this.gyqk;
	}

	public void setGyqk(String gyqk) {
		this.gyqk = gyqk;
	}

	public String getBdczh() {
		return bdczh;
	}

	public void setBdczh(String bdczh) {
		this.bdczh = bdczh;
	}

	/**
	 * @return the note
	 */
	public String getNote() {
		return note;
	}

	/**
	 * @param note the note to set
	 */
	public void setNote(String note) {
		this.note = note;
	}

	/**
	 * @return the cd00002Czr
	 */
	public String getCd00002Czr() {
		return cd00002Czr;
	}

	/**
	 * @param cd00002Czr the cd00002Czr to set
	 */
	public void setCd00002Czr(String cd00002Czr) {
		this.cd00002Czr = cd00002Czr;
	}

	/**
	 * @return the updDate
	 */
	public Date getUpdDate() {
		return updDate;
	}

	/**
	 * @param updDate the updDate to set
	 */
	public void setUpdDate(Date updDate) {
		this.updDate = updDate;
	}

	/**
	 * @return the cd00001Ssgx
	 */
	public String getCd00001Ssgx() {
		return cd00001Ssgx;
	}

	/**
	 * @param cd00001Ssgx the cd00001Ssgx to set
	 */
	public void setCd00001Ssgx(String cd00001Ssgx) {
		this.cd00001Ssgx = cd00001Ssgx;
	}

	/**
	 * @return the jysj
	 */
	public Date getJysj() {
		return jysj;
	}

	/**
	 * @param jysj the jysj to set
	 */
	public void setJysj(Date jysj) {
		this.jysj = jysj;
	}

}
